// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Aircraft struct {
	ID string `json:"id"`
}

func (Aircraft) IsEntity() {}

type Mutation struct {
}

type Query struct {
}
