package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"time"

	"github.com/edinstance/distributed-aviation-system/services/flights/internal/database/models"
	graphql1 "github.com/edinstance/distributed-aviation-system/services/flights/internal/graphql"
	"github.com/edinstance/distributed-aviation-system/services/flights/internal/graphql/model"
	"github.com/edinstance/distributed-aviation-system/services/flights/internal/logger"
	"github.com/google/uuid"
)

// ID is the resolver for the id field.
func (r *flightResolver) ID(ctx context.Context, obj *models.Flight) (string, error) {
	return obj.ID.String(), nil
}

// Aircraft is the resolver for the aircraft field.
func (r *flightResolver) Aircraft(ctx context.Context, obj *models.Flight) (*model.Aircraft, error) {
	if obj.AircraftID == uuid.Nil {
		logger.Info("the flight does not have an aircraft id")
		return nil, nil
	}
	logger.Debug("the flight had an aircraft id: ", obj.AircraftID)

	return &model.Aircraft{
		ID: obj.AircraftID.String(),
	}, nil
}

// CreateFlight is the resolver for the createFlight field.
func (r *mutationResolver) CreateFlight(ctx context.Context, number string, origin string, destination string, departureTime time.Time, arrivalTime time.Time, aircraftID string) (*models.Flight, error) {
	parsedAircraftId, err := uuid.Parse(aircraftID)
	if err != nil {
		return nil, err
	}

	return r.Resolver.CreateFlightResolver.CreateFlight(
		ctx,
		number,
		origin,
		destination,
		departureTime,
		arrivalTime,
		parsedAircraftId,
	)
}

// GetFlightByID is the resolver for the getFlightById field.
func (r *queryResolver) GetFlightByID(ctx context.Context, id string) (*models.Flight, error) {
	return r.Resolver.GetFlightResolver.GetFlightById(ctx, id)
}

// Flight returns graphql1.FlightResolver implementation.
func (r *Resolver) Flight() graphql1.FlightResolver { return &flightResolver{r} }

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type flightResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
