package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.79

import (
	"context"
	"time"

	"github.com/edinstance/distributed-aviation-system/services/flights/internal/database/models"
	graphql1 "github.com/edinstance/distributed-aviation-system/services/flights/internal/graphql"
)

// ID is the resolver for the id field.
func (r *flightResolver) ID(ctx context.Context, obj *models.Flight) (string, error) {
	return obj.ID.String(), nil
}

// CreateFlight is the resolver for the createFlight field.
func (r *mutationResolver) CreateFlight(ctx context.Context, number string, origin string, destination string, departureTime time.Time, arrivalTime time.Time) (*models.Flight, error) {
	return r.Resolver.CreateFlightResolver.CreateFlight(
		ctx,
		number,
		origin,
		destination,
		departureTime,
		arrivalTime,
	)
}

// Flight returns graphql1.FlightResolver implementation.
func (r *Resolver) Flight() graphql1.FlightResolver { return &flightResolver{r} }

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

type flightResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
