"""
Django settings for authentication project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import json
import logging
from datetime import timedelta
from pathlib import Path

import structlog
from decouple import config

from common.jwt_helper import load_signing_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,*', cast=lambda v: [s.strip() for s in v.split(',')])

# Application definition
SHARED_APPS = [
    "django_tenants",
    "organizations",  # registry (public schema)
    "django.contrib.contenttypes",
    "django.contrib.auth",  # keep permissions framework shared
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

TENANT_APPS = [
    "users",  # tenant‑specific user tables
    "authapi",
    "django.contrib.sessions",  # sessions per tenant
    "django.contrib.admin",  # admin per tenant → fixes the error
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_structlog",
]

# Combine them for Django
INSTALLED_APPS = SHARED_APPS + TENANT_APPS

MIDDLEWARE = [
    "common.middleware.header_tenant_middleware.HeaderTenantMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "common.middleware.logging_middleware.EnhancedLoggingMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "authentication.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "authentication.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": config("DATABASE_NAME", default="authentication"),
        "USER": config("DATABASE_USER", default="postgres"),
        "PASSWORD": config("DATABASE_PASSWORD", default="postgres"),
        "HOST": config("DATABASE_HOST", default="localhost"),
        "PORT": config("DATABASE_PORT", default="5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Django Tenants
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

TENANT_MODEL = "organizations.Organization"

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# JWT Settings
def load_verifying_key():
    """Load the RSA public key for JWT verification."""
    keys_dir = config("KEYS_DIR", default="/keys")
    keymap_path = f"{keys_dir}/keymap.json"
    public_key_path = f"{keys_dir}/public.pem"

    try:
        with open(keymap_path) as f:
            keymap = json.load(f)
        active_entry = next((v for v in keymap.values() if v.get("active")), None)
        if active_entry:
            public_key_path = f"{keys_dir}/{active_entry.get('public', 'public.pem')}"
    except (FileNotFoundError, json.JSONDecodeError):
        pass

    with open(public_key_path, "r") as f:
        key_content = f.read()

    if key_content and not key_content.startswith("-----BEGIN"):
        raise ValueError("Invalid PEM format")
    return key_content


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "RS256",
    "SIGNING_KEY": load_signing_key(),
    "VERIFYING_KEY": load_verifying_key(),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("common.jwt.tokens.CustomAccessToken",),
    'USER_ID_CLAIM': 'sub',
    'USER_ID_FIELD': 'id',
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000",
    cast=lambda v: [s.strip() for s in v.split(",")],
)
CORS_ALLOW_CREDENTIALS = config("CORS_ALLOW_CREDENTIALS", default=True, cast=bool)
CORS_ALLOWED_HEADERS = config(
    "CORS_ALLOWED_HEADERS",
    default="accept,accept-encoding,authorization,content-type,dnt,origin,user-agent,x-csrftoken,x-requested-with,x-tenant-id",
    cast=lambda v: [s.strip() for s in v.split(",")],
)
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Logging Configuration
LOG_LEVEL = config("LOG_LEVEL", default="INFO")

# OpenTelemetry Configuration
OTEL_SERVICE_NAME = config("OTEL_SERVICE_NAME", default="authentication-service")
OTEL_EXPORTER_OTLP_ENDPOINT = config("OTEL_EXPORTER_OTLP_ENDPOINT", default="http://localhost:4317")
OTEL_EXPORTER_OTLP_PROTOCOL = config("OTEL_EXPORTER_OTLP_PROTOCOL", default="grpc")
OTEL_TRACES_EXPORTER = config("OTEL_TRACES_EXPORTER", default="otlp")
OTEL_METRICS_EXPORTER = config("OTEL_METRICS_EXPORTER", default="otlp")
OTEL_LOGS_EXPORTER = config("OTEL_LOGS_EXPORTER", default="otlp")
OTEL_METRIC_EXPORT_INTERVAL = config("OTEL_METRIC_EXPORT_INTERVAL", default=5000, cast=int)
OTEL_BSP_SCHEDULE_DELAY = config("OTEL_BSP_SCHEDULE_DELAY", default=5000, cast=int)

# Structured logging with structlog
structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.make_filtering_bound_logger(logging.DEBUG),
    logger_factory=structlog.stdlib.LoggerFactory(),
    context_class=dict,
    cache_logger_on_first_use=True,
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.JSONRenderer(),
        },
    },
    "handlers": {
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django_structlog": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "authentication": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "users": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "organizations": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "authapi": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
}
